export const bdProducts = [
  {
    id: 0,
    title: "Purple Haze",
    imageUrl: "/BlackMarket/Img/products/purple-haze.jpg",
    description:
      "Легендарная сатива с ягодными нотками и мощным творческим эффектом. 22% ТГК.",
    price: 42.5,
    categories: 1,
  },
  {
    id: 1,
    title: "Northern Lights",
    imageUrl: "/BlackMarket/Img/products/northern-lights.jpg",
    description:
      "Чистая индика с афганской генетикой. Идеально для глубокой релаксации и сна.",
    price: 39.99,
    categories: 1,
  },
  {
    id: 2,
    title: "GSC",
    imageUrl:
      "/BlackMarket/Img/products/THCa-COOKIES-LD-HYBRID-EuphoriaCBD.png",
    description:
      "Сбалансированный гибрид с десертным вкусом и мощным эйфорическим эффектом.",
    price: 48.9,
    categories: 1,
  },
  {
    id: 3,
    title: "Афганский гашиш",
    imageUrl: "/BlackMarket/Img/products/kabul.png",
    description:
      "Черный мягкий гашиш, ручная работа. Классический опийный вкус.",
    price: 29.99,
    categories: 1,
  },
  {
    id: 4,
    title: "Марокканский гашиш",
    imageUrl: "/BlackMarket/Img/products/marijuana-moroccan-hash-cannabis.png",
    description: "Прессованные трихомы светлого цвета. Мягкий и пластичный.",
    price: 24.99,
    categories: 1,
  },
  {
    id: 5,
    title: "CBD Tincture",
    imageUrl: "/BlackMarket/Img/products/lazy-river-our-products-tincture.png",
    description:
      "Жидкий экстракт каннабиса для приема внутрь. Высокое содержание КБД.",
    price: 34.99,
    categories: 1,
  },
  {
    id: 6,
    title: "CBD Oil 10%",
    imageUrl: "/BlackMarket/Img/products/cbd-oil-plain-cannabis.png",
    description:
      "Масло с высоким содержанием КБД для снятия тревоги и воспалений.",
    price: 54.99,
    categories: 1,
  },
  {
    id: 7,
    title: "Live Resin",
    imageUrl:
      "/BlackMarket/Img/products/REV_Concentrate_Paradise_Live_Jelly.png",
    description:
      "Концентрат каннабиса из замороженных шишек. Высокая терпеновая насыщенность.",
    price: 79.95,
    categories: 1,
  },
  {
    id: 8,
    title: "Green Crack",
    imageUrl:
      "/BlackMarket/Img/products/Green-Crack-strain-medical-marijuana-bud.png",
    description:
      "Бодрящий сорт для продуктивного рабочего дня. Цитрусовый аромат.",
    price: 44.95,
    categories: 1,
  },
  {
    id: 9,
    title: "Bubble Hash",
    imageUrl: "/BlackMarket/Img/products/bubble-hash-quality-grades.png",
    description: "Гидропонный гашиш высшего качества, полный распад.",
    price: 61.0,
    categories: 1,
  },
  {
    id: 10,
    title: "Jack Herer",
    imageUrl: "/BlackMarket/Img/products/Jack-Herer.png",
    description:
      "Землистый вкус с сосновыми нотами. Эффект 70% sativa / 30% indica.",
    price: 40.0,
    categories: 1,
  },
  {
    id: 11,
    title: "GDP",
    imageUrl: "/BlackMarket/Img/products/Granddaddy-Purple-Appeal.webp",
    description: "Индика с сильным седативным эффектом. Вкус винограда и ягод.",
    price: 52.0,
    categories: 1,
  },
  {
    id: 12,
    title: "Cannabis",
    imageUrl: "/BlackMarket/Img/products/cannabis-live-rosin.jpg",
    description:
      "Чистый концентрат, полученный термопрессованием. Янтарный цвет.",
    price: 69.99,
    categories: 1,
  },
  {
    id: 13,
    title: "Blueberry",
    imageUrl: "/BlackMarket/Img/products/blueberry.png",
    description:
      "Индика-доминант с запахом черники. Мощный расслабляющий эффект.",
    price: 38.99,
    categories: 1,
  },
  {
    id: 14,
    title: "Sour D",
    imageUrl: "/BlackMarket/Img/products/Sour-Diesel-cannabis-strain.webp",
    description: "Сатива с дизельным ароматом. Долгий творческий хай.",
    price: 47.9,
    categories: 1,
  },
  {
    id: 15,
    title: "Амфетамин сульфат",
    imageUrl: "/BlackMarket/Img/products/таблетки-амфетамина.png",
    description: "Белый кристаллический порошок стимулятора CNS. Чистота 72%.",
    price: 49.99,
    categories: 2,
  },
  {
    id: 16,
    title: "Метамфетамин",
    imageUrl: "/BlackMarket/Img/products/метамфетамин.png",
    description:
      "Голубоватые кристаллы высокой чистоты (95%+). Для курения или инъекций.",
    price: 119.95,
    categories: 2,
  },
  {
    id: 17,
    title: "Кокаин гидрохлорид",
    imageUrl:
      "/BlackMarket/Img/products/illicit-white-powder-in-a-bag-Getty.png",
    description:
      "Колумбийский экспорт. Белый кристаллический порошок с характерным блеском.",
    price: 129.99,
    categories: 2,
  },
  {
    id: 18,
    title: "Декспамфетамин",
    imageUrl: "/BlackMarket/Img/products/Dexedrine.png",
    description:
      "Фармацевтические таблетки 10 мг, аналог Adderall. Блистер 20 шт.",
    price: 79.99,
    categories: 2,
  },
  {
    id: 19,
    title: "Риталин",
    imageUrl: "/BlackMarket/Img/products/Метилфенидат-Риталин.png",
    description: "Ноотропный стимулятор центральной нервной системы.",
    price: 89.99,
    categories: 2,
  },
  {
    id: 20,
    title: "α-PVP",
    imageUrl: "/BlackMarket/Img/products/alfa.png",
    description: "Синтетический катинон. Жесткая психостимуляция.",
    price: 54.99,
    categories: 2,
  },
  {
    id: 21,
    title: "4-MMC",
    imageUrl: "/BlackMarket/Img/products/Мефедрон.png",
    description: "Кристаллический стимулятор и эмпатоген. 'Снежный драйв'.",
    price: 74.99,
    categories: 2,
  },
  {
    id: 22,
    title: "Эфедрин",
    imageUrl: "/BlackMarket/Img/products/efedrin-hidroklorur-osel.png",
    description:
      "Стимулятор и предшественник. Применяется в медицине и как допинг.",
    price: 39.95,
    categories: 2,
  },
  {
    id: 23,
    title: "Крэк",
    imageUrl: "/BlackMarket/Img/products/крэк-кокаин.png",
    description: "Готовые камешки для курения. Мгновенный приход.",
    price: 99.99,
    categories: 2,
  },
  {
    id: 24,
    title: "Модафинил",
    imageUrl: "/BlackMarket/Img/products/Modafinil.png",
    description: "Ноотроп для повышения когнитивных способностей и бодрости.",
    price: 45.0,
    categories: 2,
  },
  {
    id: 25,
    title: "3-FPM",
    imageUrl: "/BlackMarket/Img/products/3-fpm.png",
    description: "Функциональный стимулятор. Повышает концентрацию и энергию.",
    price: 64.99,
    categories: 2,
  },
  {
    id: 26,
    title: "2-FMA",
    imageUrl: "/BlackMarket/Img/products/2FMA.png",
    description: "Мощный стимулятор для работы или учебы на 10+ часов.",
    price: 59.99,
    categories: 2,
  },
  {
    id: 27,
    title: "Гептаминол",
    imageUrl: "/BlackMarket/Img/products/Heptaminol.png",
    description:
      "Стимулятор центральной нервной системы. Повышает физическую выносливость.",
    price: 69.95,
    categories: 2,
  },
  {
    id: 28,
    title: "Центредин",
    imageUrl: "/BlackMarket/Img/products/etamivan-toxicology.png",
    description: "Аналептик, стимулятор дыхательного центра.",
    price: 34.99,
    categories: 2,
  },
  {
    id: 29,
    title: "Оксикодон IR",
    imageUrl: "/BlackMarket/Img/products/оксикодон.png",
    description:
      "Сильнодействующий опиоидный анальгетик. Таблетки с немедленным высвобождением.",
    price: 34.99,
    categories: 3,
  },
  {
    id: 30,
    title: "Морфин сульфат",
    imageUrl: "/BlackMarket/Img/products/lechenie-pristrastyavane-morfin.png",
    description: "Ампулы для внутривенного введения. 10 мг/мл.",
    price: 69.99,
    categories: 3,
  },
  {
    id: 31,
    title: "Трамадол HCL",
    imageUrl: "/BlackMarket/Img/products/tramadol.png",
    description: "Опиоидный анальгетик центрального действия.",
    price: 14.99,
    categories: 3,
  },
  {
    id: 32,
    title: "Алпразолам",
    imageUrl: "/BlackMarket/Img/products/Алпразолам-Ксанакс-25-мг.png",
    description: "Бензодиазепин с сильным анксиолитическим действием.",
    price: 19.99,
    categories: 3,
  },
  {
    id: 33,
    title: "Героин №4",
    imageUrl: "/BlackMarket/Img/products/white-heroin.png",
    description: "Растворимый белый порошок диацетилморфина.",
    price: 129.99,
    categories: 3,
  },
  {
    id: 34,
    title: "Фентанил пластырь",
    imageUrl: "/BlackMarket/Img/products/fentanyl-patch.png",
    description: "Опиоидный анальгетик для трансдермального введения.",
    price: 149.99,
    categories: 3,
  },
  {
    id: 35,
    title: "Кодеин фосфат",
    imageUrl: "/BlackMarket/Img/products/codeine.png",
    description: "Слабый опиоид в виде белых таблеток.",
    price: 11.99,
    categories: 3,
  },
  {
    id: 36,
    title: "Диазепам",
    imageUrl: "/BlackMarket/Img/products/diazepam.png",
    description: "Бензодиазепин. Анксиолитик, противосудорожное.",
    price: 9.99,
    categories: 3,
  },
  {
    id: 37,
    title: "Гидрокодон битартрат",
    imageUrl: "/BlackMarket/Img/products/hydrocodone.png",
    description:
      "Vicodin 10/325. Опиоидный анальгетик с ацетаминофеном. Блистер 15 шт.",
    price: 29.99,
    categories: 3,
  },
  {
    id: 38,
    title: "Тапентадол",
    imageUrl: "/BlackMarket/Img/products/aspadol-tapentadol.png",
    description: "Современный опиоид. Двойной механизм действия.",
    price: 24.99,
    categories: 3,
  },
  {
    id: 39,
    title: "Метадон",
    imageUrl: "/BlackMarket/Img/products/methadone.png",
    description: "Опиоид, используемый для заместительной терапии.",
    price: 19.99,
    categories: 3,
  },
  {
    id: 40,
    title: "Клоназепам",
    imageUrl: "/BlackMarket/Img/products/Clonazepam-2-mg.png",
    description: "Противосудорожный препарат из группы бензодиазепинов.",
    price: 13.99,
    categories: 3,
  },
  {
    id: 41,
    title: "Прегабалин",
    imageUrl: "/BlackMarket/Img/products/Pregabalin-Lyrica-150-mg.png",
    description:
      "Габапентиноид. Применяется при невропатической боли и тревоге.",
    price: 17.99,
    categories: 3,
  },
  {
    id: 42,
    title: "МДМА кристаллы",
    imageUrl: "/BlackMarket/Img/products/MDMA-crystals.png",
    description: "Кристаллический порошок. Чистый сассафрас.",
    price: 84.95,
    categories: 4,
  },
  {
    id: 43,
    title: "Кетамин",
    imageUrl: "/BlackMarket/Img/products/ketamin.png",
    description: "Белый кристаллический порошок. Диссоциатив.",
    price: 64.99,
    categories: 4,
  },
  {
    id: 44,
    title: "ДМТ",
    imageUrl: "/BlackMarket/Img/products/dmt.png",
    description: "Желтоватые кристаллы. Мощный психоделик короткого действия.",
    price: 94.99,
    categories: 4,
  },
  {
    id: 45,
    title: "2C-B (Нексус)",
    imageUrl: "/BlackMarket/Img/products/2cb.png",
    description: "Фенетиламин. Таблетки с логотипами.",
    price: 29.99,
    categories: 4,
  },
  {
    id: 46,
    title: "МДА (Sally)",
    imageUrl: "/BlackMarket/Img/products/Ecstasy-Pills.png",
    description: "Эмпатоген + легкие визуалы.",
    price: 74.99,
    categories: 4,
  },
  {
    id: 47,
    title: "GHB",
    imageUrl: "/BlackMarket/Img/products/GHB.png",
    description: "Жидкость в пузырьке. Депрессант.",
    price: 34.99,
    categories: 4,
  },
  {
    id: 48,
    title: "Псилоцибиновые грибы",
    imageUrl: "/BlackMarket/Img/products/Psilocybin-crystals.png",
    description: "Сушеные грибы Psilocybe Cubensis. Эффект 4-6 часов.",
    price: 39.99,
    categories: 4,
  },
  {
    id: 49,
    title: "5-MeO-DMT",
    imageUrl: "/BlackMarket/Img/products/5-MeO-DMT.png",
    description:
      "Кристаллический порошок из жаб жабы. Кратковременный, но очень мощный.",
    price: 149.99,
    categories: 4,
  },
  {
    id: 50,
    title: "Мескалин HCL",
    imageUrl: "/BlackMarket/Img/products/Mescaline-HCL.png",
    description: "Психоделик из кактуса Сан-Педро. Эффект 12-14 часов.",
    price: 109.99,
    categories: 4,
  },
  {
    id: 51,
    title: "JWH-018",
    imageUrl: "/BlackMarket/Img/products/JWH-018.png",
    description: "Синтетический каннабиноид. Белый порошок.",
    price: 44.95,
    categories: 5,
  },
  {
    id: 52,
    title: "MAM-2201",
    imageUrl: "/BlackMarket/Img/products/MAM-2201.png",
    description: "Мощный агонист каннабиноидных рецепторов.",
    price: 49.99,
    categories: 5,
  },
  {
    id: 53,
    title: "MDPHP ",
    imageUrl: "/BlackMarket/Img/products/MDPHP.png",
    description: "Синтетический катинон. Долгий стимулирующий эффект.",
    price: 64.99,
    categories: 5,
  },
  {
    id: 54,
    title: "3-MMC",
    imageUrl: "/BlackMarket/Img/products/3-mmc.png",
    description: "Катинон. Мягкий стимулятор с эмпатогенными свойствами.",
    price: 69.99,
    categories: 5,
  },
  {
    id: 55,
    title: "MXE",
    imageUrl: "/BlackMarket/Img/products/MXE.png",
    description: "Диссоциатив. Порошок для диссоциации.",
    price: 79.99,
    categories: 5,
  },
  {
    id: 56,
    title: "2-FDCK",
    imageUrl: "/BlackMarket/Img/products/2-FDCK.png",
    description: "Аналог кетамина, мягче и с более длительным действием.",
    price: 59.99,
    categories: 5,
  },
  {
    id: 57,
    title: "25I-NBOMe",
    imageUrl: "/BlackMarket/Img/products/25I-NBOMe.png",
    description: "Мощный галлюциноген, часто распространяемый как ЛСД.",
    price: 24.99,
    categories: 5,
  },
  {
    id: 58,
    title: "Spice Paper K2",
    imageUrl: "/BlackMarket/Img/products/Spice-Paper-K2.png",
    description: "Травяная смесь с синтетическими каннабиноидами.",
    price: 29.99,
    categories: 5,
  },
  {
    id: 59,
    title: "Карфентанил порошок",
    imageUrl: "/BlackMarket/Img/products/Carfentanil-powder.png",
    description:
      "Очень сильный опиоид для ветеринарии. Только для исследований!",
    price: 199.99,
    categories: 5,
  },
  {
    id: 60,
    title: "U-47700",
    imageUrl: "/BlackMarket/Img/products/U-47700.png",
    description: "Синтетический опиоид, розовый порошок.",
    price: 89.99,
    categories: 5,
  },
  {
    id: 61,
    title: "Eutylone",
    imageUrl: "/BlackMarket/Img/products/Eutylone.png",
    description: "Синтетический катинон, аналог метилона и этилона.",
    price: 79.99,
    categories: 5,
  },
];
